config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/:controller(/:action(/:id))'
  get 'startrekdeepspacenine/characters', :controller => 'categories', :action => 'show', :id => 6, :as => :st_ds9_chars
  get 'startrekvoyager/episodes', :controller => 'categories', :action => 'show', :id => 2, :as => :st_voy_eps
  get 'startrekdeepspacenine/episodes', :controller => 'categories', :action => 'show', :id => 4, :as => :st_ds9_eps
  get 'startrekthenextgeneration/episodes', :controller => 'categories', :action => 'show', :id => 11, :as => :st_tng_eps
  get 'doctorwho/episodes', :controller => 'categories', :action => 'show', :id => 14, :as => :drw_eps

  get 'startrekvoyager/characters', :controller => 'categories', :action => 'show', :id => 5, :as => :st_voy_chars
  get 'startrekthenextgeneration/characters', :controller => 'categories', :action => 'show', :id => 12, :as => :st_tng_chars
  get 'doctorwho/characters', :controller => 'categories', :action => 'show', :id => 15, :as => :drw_chars

  post 'items/vote/:id', :controller => "items", :action => "vote"
  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_tree
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :category
	has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_headers

  layout "application"

  protected

  def set_headers
    @header1 = 'Sci-Fi Voter'
    @header2 = ''
    @header3 = ''
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    list
    render :action => 'list'
  end

  def list
    @header2 = "Vote on things!"
  end

  def show
    @category = Category.find(params[:id])

    if @category.parent
      @header2 = @category.parent.name
      @header3 = @category.name
    else
      @header2 = @category.name
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def vote
    item = Item.find(params[:id])

    if item.votes.find_by_ip_address(request.remote_ip)
      # do nothing because this ip address has already voted
    else
      value = params[:value].to_i > 0 ? 1 : -1

      item.votes.create :value => value, :ip_address => request.remote_ip
      item.net_votes += value
      item.save
    end

    render body: nil
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def google_chart (items = [], title = '')
    chart = {}
    chart[:size]   = '&amp;chs='        # 200x300
    chart[:data]   = '&amp;chd=t:'      # 0.0,1.1|2,3
    chart[:type]   = '&amp;cht='        # bvg
    chart[:axes]   = '&amp;chxt='       # y,x,x,r,t
    chart[:labels] = '&amp;chxl='       # 0:||Votes|2:||Season|
    chart[:color]  = '&amp;chco=55AA55'
    chart_array = []

    case items.first.fields
    when /\d+x\d+/ # charting TV show episodes
      for item in items
        season = item.fields.to_i - 1
        chart_array[season] = 0 unless chart_array[season]
        chart_array[season] += item.net_votes
      end
      chart_array.map! {|v| v < 0 ? 0 : v}
      max = [chart_array.max, 1].max
      chart_array.map! {|v| (v.to_f / max * 100).to_i}

      chart[:size]   += (chart_array.size * 50).to_s + 'x200'
      chart[:data]   += chart_array.join(',')
      chart[:type]   += 'bvg'
      chart[:axes]   += 'y,x,x'
      chart[:labels] += '0:||Net+Votes|1:|' + (1..(chart_array.size)).to_a.join('|') + '|2:||Season|'
    else
      return
    end

    url = 'http://chart.apis.google.com/chart?chtt=' + title.sub(/ /,'+')
    chart.each_value {|v| url += v}
    '<img src="' + url + '" />'
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_vote_js.html.erb
<script type='text/javascript'>
  try {
    $("vote_up_<%= id %>").onsubmit = function(){
      beforeVote(<%= id %>);
      afterVote(<%= id %>, 1);
      new Ajax.Request('/items/vote/<%= id %>?value=1');
      return false;
    };
    $("vote_down_<%= id %>").onsubmit = function(){
      beforeVote(<%= id %>);
      afterVote(<%= id %>, -1);
      new Ajax.Request('/items/vote/<%= id %>?value=-1');
      return false;
    };
  } catch(err) {}
</script>

app/views/categories/list.haml
%ul
  %li
    Star Trek: Deep Space Nine
    %ul
      %li= link_to "Characters", st_ds9_chars_url
      %li= link_to "Episodes", st_ds9_eps_url
  %li
    Star Trek: The Next Generation
    %ul
      %li= link_to "Characters", st_tng_chars_url
      %li= link_to "Episodes", st_tng_eps_url
  %li
    Star Trek: Voyager
    %ul
      %li= link_to "Characters", st_voy_chars_url
      %li= link_to "Episodes", st_voy_eps_url
  %li
    Doctor Who
    %ul
      %li= link_to "Characters", drw_chars_url
      %li= link_to "Episodes", drw_eps_url

app/views/categories/show.haml
- if @category.items.size > 0
  %p
    = (google_chart(@category.items) || "").html_safe
  %table.sortable
    %thead
      %tr
        %th.sortfirstdesc.number Net Votes
        - for header in @category.headers.split('::')
          %th.text= header
        %th.nosort= "?"
        %th{:class => "nosort", :style => "width: 100px;"} Cast Vote
    %tbody
      - for item in @category.items
        %tr
          %td
            %div{:class => "netVotes", :id => "netVotes_#{item.id}"}= item.net_votes
          - for field in item.fields.split('::')
            %td= field
          %td
            - if item.tooltip
              = item.tooltip
          %td
            - unless item.votes.find_by_ip_address(request.remote_ip)
              %div{:id => "promoteDemote_#{item.id}"}
                = form_with(:url => {:controller => :items, :action => :vote, :id => item, :value => 1}, :id => "vote_up_#{item.id}", :before => "beforeVote(#{item.id})", :after => "afterVote(#{item.id}, 1)") do
                  = submit_tag "+", :class => "promoteDemote promote"
                = form_with(:url => {:controller => :items, :action => :vote, :id => item, :value => -1}, :id => "vote_down_#{item.id}", :before => "beforeVote(#{item.id})", :after => "afterVote(#{item.id}, -1)") do
                  = submit_tag "-", :class => "promoteDemote demote"
            = render "vote_js", :id => item.id

- else
  This category is empty.

app/views/layouts/applicatio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScifiVoterRails5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScifiVoterRails5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
%html
  -# = javascript_include_tag :defaults
  -# = javascript_include_tag 'tablekit'
  = javascript_include_tag 'application'

  -# = stylesheet_link_tag 'voter'
  = stylesheet_link_tag 'application', media: 'all'
  -# = stylesheet_link_tag 'tablekit'

  %title= @header1 + ' - ' + @header2 + ( @header3 == '' ? '' : ' - ' + @header3 )

  %body
    %p= link_to "<< back to Philip Brocoum's home page", "http://www.PhilipBrocoum.com"
    %h1= link_to @header1, "/"
    %h2= @header2
    %h3= @header3

    %p I originally created this for my own amusement, and I have to say I'm shocked by how accurate the votes turned out to be.
    = yield

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>